### ISSUE TITLE
AttributeError: 'Box' object has no attribute 'np_random'

### ISSUE THREAD

**Issue by xjz89982** [amazon-research/meta-q-learning#2]
Hello, i ran the code with the command `python run_script.py --env cheetah-dir --gpu_id 0 --seed 0` but got an errror. The error message was:
```
/home/xw/gym/gym/logger.py:30: UserWarning: WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "main.py", line 495, in <module>
    env = make_env(args)
  File "main.py", line 154, in make_env
    params = eparams,
  File "/home/xw/meta-q-learning/misc/env_meta.py", line 35, in build_PEARL_envs
    env.action_space.np_random.seed(seed)
AttributeError: 'Box' object has no attribute 'np_random`
```
I've searched on the Internet. It seems to be an error related to gym, but i don't know how to solve it. Could you help me? Thanks.

**Comment by rasoolfa** [comment]
that is likely due to gym version. Try with gym==0.12.5 or gym==0.13.

Hope that helps.
